// Generated by create-bible-extension. Describes the sandbox realm
// your extension runs in. Safe to extend, but adding a declaration here does
// not add the capability — the realm has to actually provide it.

/**
 * Routed to the host and written to your extension's log, which you can read
 * from the app's extension details view. There is no stdout in the realm.
 */
declare const console: {
  log(...args: unknown[]): void;
  info(...args: unknown[]): void;
  warn(...args: unknown[]): void;
  error(...args: unknown[]): void;
  debug(...args: unknown[]): void;
  trace(...args: unknown[]): void;
};

/** Timers are driven by the host; ids are opaque numbers, not Node Timeouts. */
declare function setTimeout(handler: () => void, timeoutMs?: number): number;
declare function clearTimeout(id: number): void;
declare function setInterval(handler: () => void, intervalMs?: number): number;
declare function clearInterval(id: number): void;

/** Runs on the realm's own job queue — no host clock involved. */
declare function queueMicrotask(callback: () => void): void;
